### ISSUE TITLE
Problem running the module (as it is) on 2.5.5 Final and 3.1.0 Final

### ISSUE THREAD

**Issue by braoru** [cloudtrust/keycloak-wsfed#1]
I have problem running the current code as a module (at least not as easily as other example/small modules).

As it is within keycloak 2.5.5 Final 

```bash
./bin/jboss-cli.sh --command="module add --name=com.quest.keycloak-wsfed --resources=./keycloak-wsfed-2.5.5.Final.jar --dependencies=org.keycloak.keycloak-server-spi,org.keycloak.keycloak-server-spi-private,org.keycloak.keycloak-saml-core,org.keycloak.keycloak-services,org.picketlink.picketlink-federation,org.picketlink.picketlink-common,org.apache.commons.commons-lang3,org.jboss.resteasy.resteasy-jaxrs"
```

Adding the registration line to standalone.xml

```xml
<providers>
    <provider>module:com.quest.keycloak-wsfed</provider>
</providers>
```

Get this error

```
10:14:15,379 ERROR [org.jboss.msc.service.fail] (ServerService Thread Pool -- 48) MSC000001: Failed to start service jboss.undertow.deployment.default-server.default-host./auth: org.jboss.msc.service.StartException in service jboss.undertow.deployment.default-server.default-host./auth: java.lang.RuntimeException: RESTEASY003325: Failed to construct public org.keycloak.services.resources.KeycloakApplication(javax.servlet.ServletContext,org.jboss.resteasy.core.Dispatcher)
	at org.wildfly.extension.undertow.deployment.UndertowDeploymentService$1.run(UndertowDeploymentService.java:85)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)
	at org.jboss.threads.JBossThread.run(JBossThread.java:320)
Caused by: java.lang.RuntimeException: RESTEASY003325: Failed to construct public org.keycloak.services.resources.KeycloakApplication(javax.servlet.ServletContext,org.jboss.resteasy.core.Dispatcher)
	at org.jboss.resteasy.core.ConstructorInjectorImpl.construct(ConstructorInjectorImpl.java:162)
	at org.jboss.resteasy.spi.ResteasyProviderFactory.createProviderInstance(ResteasyProviderFactory.java:2209)
	at org.jboss.resteasy.spi.ResteasyDeployment.createApplication(ResteasyDeployment.java:299)
	at org.jboss.resteasy.spi.ResteasyDeployment.start(ResteasyDeployment.java:240)
	at org.jboss.resteasy.plugins.server.servlet.ServletContainerDispatcher.init(ServletContainerDispatcher.java:113)
	at org.jboss.resteasy.plugins.server.servlet.HttpServletDispatcher.init(HttpServletDispatcher.java:36)
	at io.undertow.servlet.core.LifecyleInterceptorInvocation.proceed(LifecyleInterceptorInvocation.java:117)
	at org.wildfly.extension.undertow.security.RunAsLifecycleInterceptor.init(RunAsLifecycleInterceptor.java:78)
	at io.undertow.servlet.core.LifecyleInterceptorInvocation.proceed(LifecyleInterceptorInvocation.java:103)
	at io.undertow.servlet.core.ManagedServlet$DefaultInstanceStrategy.start(ManagedServlet.java:231)
	at io.undertow.servlet.core.ManagedServlet.createServlet(ManagedServlet.java:132)
	at io.undertow.servlet.core.DeploymentManagerImpl.start(DeploymentManagerImpl.java:526)
	at org.wildfly.extension.undertow.deployment.UndertowDeploymentService.startContext(UndertowDeploymentService.java:101)
	at org.wildfly.extension.undertow.deployment.UndertowDeploymentService$1.run(UndertowDeploymentService.java:82)
	... 6 more
Caused by: java.lang.RuntimeException: org.jboss.modules.ModuleNotFoundException: com.quest.keycloak-wsfed:main
	at org.keycloak.provider.wildfly.ModuleProviderLoaderFactory.create(ModuleProviderLoaderFactory.java:44)
	at org.keycloak.provider.ProviderManager.<init>(ProviderManager.java:59)
	at org.keycloak.services.DefaultKeycloakSessionFactory.init(DefaultKeycloakSessionFactory.java:74)
	at org.keycloak.services.resources.KeycloakApplication.createSessionFactory(KeycloakApplication.java:313)
	at org.keycloak.services.resources.KeycloakApplication.<init>(KeycloakApplication.java:110)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.jboss.resteasy.core.ConstructorInjectorImpl.construct(ConstructorInjectorImpl.java:150)
	... 19 more
Caused by: org.jboss.modules.ModuleNotFoundException: com.quest.keycloak-wsfed:main
	at org.jboss.modules.ModuleLoader.loadModule(ModuleLoader.java:223)
	at org.keycloak.provider.wildfly.ModuleProviderLoaderFactory.create(ModuleProviderLoaderFactory.java:40)
	... 28 more
```

I've also tried by moving dependencies to 3.1.0.Final & fixing what was crashing at the compile time then

```Bash
./bin/jboss-cli.sh --command="module add --name=com.quest.keycloak-wsfed --resources=./keycloak-wsfed-3.1.0.Final.jar --dependencies=org.keycloak.keycloak-server-spi,org.keycloak.keycloak-server-spi-private,org.keycloak.keycloak-saml-core,org.keycloak.keycloak-services,org.picketlink.picketlink-federation,org.picketlink.picketlink-common,org.apache.commons.commons-lang3,org.jboss.resteasy.resteasy-jaxrs"
```

But I end with exactly the same error.

**Comment by dbarentine** [comment]
So the exception "ModuleNotFoundException: com.quest.keycloak-wsfed:main" says to me that your module isn't installed correctly. The class loader can't find the one you created.

Are you using the downloaded KC 2.5.5.Final package or are you overlaying the files onto a Wildfly or JBoss instance? If so what version of Wildfly?

I've run your steps on the full Keycloak packaged 2.5.5.Final with Wildfly instance and it drops the module into <WILDFLY_HOME>/modules/com... That seems to work although I would probably drop it into my own layer. But you should verify that it actually installed it into the modules directory first.

The second part is your dependencies for the module are incorrect. Specifically the Picketlink ones (at least on mine) and you need saml-core-public and jboss logging. It should look like:
`<module xmlns="urn:jboss:module:1.1" name="com.quest.keycloak-wsfed">

    <resources>
        <resource-root path="keycloak-wsfed-2.5.5.Final.jar"/>
    </resources>

    <dependencies>
        <module name="org.keycloak.keycloak-server-spi"/>
        <module name="org.keycloak.keycloak-server-spi-private"/>
        <module name="org.keycloak.keycloak-saml-core"/>
        <module name="org.keycloak.keycloak-saml-core-public"/>
        <module name="org.keycloak.keycloak-services"/>
        <module name="org.picketlink.federation"/>
        <module name="org.picketlink.common"/>
        
        <module name="org.jboss.resteasy.resteasy-jaxrs"/>
        <module name="org.jboss.logging" />
    </dependencies>
</module>`

We need commons-lang3 but it's not a module included with Wildfly. I think it's one of the Keycloak dependencies so it may already be available to us without including it here. If you end up with class not found errors though you will need to add that module and it as a dependency here.

In your standalone.xml you will also need to add the module to the <theme> section in the KC settings. And then set the admin theme in master to wsfed.
`<modules>
    <module>
        com.quest.keycloak-wsfed
    </module>
</modules>`

The other option is just to skip all of this and drop the jar into the providers directory which wouldn't require all the dependency work. That would mean you'd also have to do something similar for the theme though since it wouldn't be a module.

**Comment by dbarentine** [comment]
I should note we haven't tested this with KC 3.x. So it's likely that some work would need to be done in order to port it to the new version.

**Comment by braoru** [comment]
Thank I will try and come back !

No worry for the 3.1.0 I just need to get used to JBOSS loading (2-3 years without java and it was only self-contained services / scala :-))

The work for the 3.1.0 is our goals and I know it will take some time to do it.

**Comment by braoru** [comment]
I've tried to drop everything in providers already, I end-up with KC loading (the module get loaded) but the template of the theme seem to not be rendered. I get 404 when I want to create the provider (selecting from drop list).

**Comment by braoru** [comment]
I tested the drop in providers on version 2.5.5.Final

```Bash
09:44:21,866 ERROR [org.jboss.msc.service.fail] (ServerService Thread Pool -- 52) MSC000001: Failed to start service jboss.undertow.deployment.default-server.default-host./auth: org.jboss.msc.service.StartException in service jboss.undertow.deployment.default-server.default-host./auth: java.lang.RuntimeException: RESTEASY003325: Failed to construct public org.keycloak.services.resources.KeycloakApplication(javax.servlet.ServletContext,org.jboss.resteasy.core.Dispatcher)
	at org.wildfly.extension.undertow.deployment.UndertowDeploymentService$1.run(UndertowDeploymentService.java:85)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)
	at org.jboss.threads.JBossThread.run(JBossThread.java:320)
Caused by: java.lang.RuntimeException: RESTEASY003325: Failed to construct public org.keycloak.services.resources.KeycloakApplication(javax.servlet.ServletContext,org.jboss.resteasy.core.Dispatcher)
	at org.jboss.resteasy.core.ConstructorInjectorImpl.construct(ConstructorInjectorImpl.java:162)
	at org.jboss.resteasy.spi.ResteasyProviderFactory.createProviderInstance(ResteasyProviderFactory.java:2209)
	at org.jboss.resteasy.spi.ResteasyDeployment.createApplication(ResteasyDeployment.java:299)
	at org.jboss.resteasy.spi.ResteasyDeployment.start(ResteasyDeployment.java:240)
	at org.jboss.resteasy.plugins.server.servlet.ServletContainerDispatcher.init(ServletContainerDispatcher.java:113)
	at org.jboss.resteasy.plugins.server.servlet.HttpServletDispatcher.init(HttpServletDispatcher.java:36)
	at io.undertow.servlet.core.LifecyleInterceptorInvocation.proceed(LifecyleInterceptorInvocation.java:117)
	at org.wildfly.extension.undertow.security.RunAsLifecycleInterceptor.init(RunAsLifecycleInterceptor.java:78)
	at io.undertow.servlet.core.LifecyleInterceptorInvocation.proceed(LifecyleInterceptorInvocation.java:103)
	at io.undertow.servlet.core.ManagedServlet$DefaultInstanceStrategy.start(ManagedServlet.java:231)
	at io.undertow.servlet.core.ManagedServlet.createServlet(ManagedServlet.java:132)
	at io.undertow.servlet.core.DeploymentManagerImpl.start(DeploymentManagerImpl.java:526)
	at org.wildfly.extension.undertow.deployment.UndertowDeploymentService.startContext(UndertowDeploymentService.java:101)
	at org.wildfly.extension.undertow.deployment.UndertowDeploymentService$1.run(UndertowDeploymentService.java:82)
	... 6 more
Caused by: java.lang.RuntimeException: org.jboss.modules.ModuleNotFoundException: com.quest.keycloak-wsfed:main
	at org.keycloak.provider.wildfly.ModuleProviderLoaderFactory.create(ModuleProviderLoaderFactory.java:44)
	at org.keycloak.provider.ProviderManager.<init>(ProviderManager.java:59)
	at org.keycloak.services.DefaultKeycloakSessionFactory.init(DefaultKeycloakSessionFactory.java:74)
	at org.keycloak.services.resources.KeycloakApplication.createSessionFactory(KeycloakApplication.java:313)
	at org.keycloak.services.resources.KeycloakApplication.<init>(KeycloakApplication.java:110)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.jboss.resteasy.core.ConstructorInjectorImpl.construct(ConstructorInjectorImpl.java:150)
	... 19 more
Caused by: org.jboss.modules.ModuleNotFoundException: com.quest.keycloak-wsfed:main
	at org.jboss.modules.ModuleLoader.loadModule(ModuleLoader.java:223)
	at org.keycloak.provider.wildfly.ModuleProviderLoaderFactory.create(ModuleProviderLoaderFactory.java:40)
	... 28 more
```

I try a more cleaner declaration

**Comment by dbarentine** [comment]
Yeah that's the problem with using the provider directory when you have a theme you need. You can always drop that html partial in the: keycloak-2.5.5.Final\themes\base\admin\resources\partials and not have to load the theme via a module. But it can be a pain to do that in a real deployment.

So the key here is we need to figure out why KC/Wildfly can't find the module. This isn't actually an issue with the code but something in your module/Wildfly configuration.

On my system when I ran your command above it created the module here:
`keycloak-2.5.5.Final\modules\com\quest\keycloak-wsfed\main`

That seems to work fine on mine but you could also try dropping it into the Keycloak layer here: `keycloak-2.5.5.Final\modules\system\layers\keycloak`

Or creating your own layer (keycloak-2.5.5.Final\modules\system\layers\wsfed) and adding it to the `keycloak-2.5.5.Final\modules\layers.conf` file.

The second thing to check is that your module is actually named correctly. In the module.xml file under the main folder you should see this:
`<module xmlns="urn:jboss:module:1.1" name="com.quest.keycloak-wsfed">`

If that name is different that would cause the not found error.

If none of that works I'll create an overlay zip for keycloak-2.5.5.Final that I can send you.

**Comment by braoru** [comment]
I don't give up so easily :-) It may take me 3 month but I will make it load.

On 2.5.5 I have a module loading and the provider appearing within the dropdown list :) (it's a come-back to starting point but at least, I know how things are loaded now).

* I created manually the module.xml (as you explained) mow the module is loaded without Exceptions
* Added it as a providers in the stadalone.xml (as before)
* Added the module within the stadalone.xml is this : 
```xml
            <theme>
                <modules>
                        <module>
                                com.quest.keycloak-wsfed
                        </module>
                </modules>
                <staticMaxAge>2592000</staticMaxAge>
                <cacheThemes>true</cacheThemes>
                <cacheTemplates>true</cacheTemplates>
                <dir>${jboss.home.dir}/themes</dir>
            </theme>
```
I still have the 404 when I choose wsfed provider but I things it's a problem with the theme loading.

**Comment by braoru** [comment]
Just to clarify

```
GET /auth/resources/2.5.5.final/admin/keycloak/partials/realm-identity-provider-wsfed.html HTTP/1.1
Host: 127.0.0.1:8080
Connection: keep-alive
Pragma: no-cache
Cache-Control: no-cache
Accept: application/json, text/plain, */*
User-Agent: Mozilla/5.0 Chrome/58.0.3029.110 Safari/537.36
Referer: http://127.0.0.1:8080/auth/admin/master/console/
Accept-Encoding: gzip, deflate, sdch, br
Accept-Language: fr-CH,en-US;q=0.8,fr-FR;q=0.6,fr;q=0.4,en;q=0.2
Cookie: KEYCLOAK_STATE_CHECKER=C1UXBPgxcHvMAgk3w7wIYIKJBpf5KFWET6FYl3VNCyE

---------------------

HTTP/1.1 404 Not Found
Connection: keep-alive
X-Powered-By: Undertow/1
Server: WildFly/10
Content-Length: 0
Date: Fri, 19 May 2017 08:46:24 GMT

```

**Comment by dbarentine** [comment]
Make sure you've set the admin theme in the master realm to wsfed. Technically any realm you want to use wsfed will need to use this theme. So what you may want to do is just set your default theme in your standalone.xml.

`<theme>
   <default>extended-keycloak</default>
   ...
</theme>`

**Comment by braoru** [comment]
It works :-)

I don't know why but it's working. 

Thanks for the help ! Now I will read more about jboss modules and try to find how themes are loaded.

![image](https://cloud.githubusercontent.com/assets/1213055/26273070/36c2e06e-3d28-11e7-8229-27c00d8aa059.png)

**Comment by braoru** [comment]
Updated documentation accordingly
